global using Carter;
global using MediatR;
global using Marten;
global using BuildingBlocks.CQRS;
global using Mapster;
global using Catalog.API.Exceptions;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Routing;
global using Microsoft.AspNetCore.Builder;
